print("Curriculum Vitae")
print("Informatii Personale:")
print("Nume, Prenume:Gheorghita Eugen")
print("Adresa: Tudor Vladimirescu 12 ")
print("Email: mreugen4321@gmail.com")
print("Nationalitate: moldovean")
print("Nascut la: 06.01.2005")
print('Studii: Institutia Publica Liceul Teoretic "Mihai Eminescu" ')
print("Aptitudini si Competente personale")
print("Limba materna: romana")
print("Limbi straine cunoscute: \n Engleza - B1 \n Germana - A1 ")
print("Se atesta aptitudini si competente in cadrul lucrarii la calculator")
